DemoMaster/Models/CustomerMaster.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMaster.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class CustomerMaster
    {
        public string CustomerCode { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string StateCode { get; set; }
        public string CountryCode { get; set; }
        public string ZipCode { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string InActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }

        public List<SelectListItem> GetCountryCode { get; set; }
        public List<SelectListItem> GetStateCode { get; set; }
        public List<SelectListItem> GetCompany { get; set; }
        public int RecordCount { get; set; }
    }
}

DemoMaster/Controllers/CustomerMastersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DemoMaster.Models;
using System.Configuration;
using System.Data.SqlClient;
using System.Data.Entity.Core.Objects;
using DemoMaster.Repository;

namespace DemoMaster.Controllers
{
    public class CustomerMastersController : Controller
    {
        private FMSARABICEntities2 db = new FMSARABICEntities2();

        // GET: CustomerMasters
        public ActionResult Index()
        {
            return View(db.CustomerMaster.ToList());
        }

        // GET: CustomerMasters/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustomerMaster customerMaster = db.CustomerMaster.Find(id);
            if (customerMaster == null)
            {
                return HttpNotFound();
            }
            return View(customerMaster);
        }

        // GET: CustomerMasters/Create
        public ActionResult Create()
        {
            CustomerMaster GetValue = new CustomerMaster();
            GetValue.GetCountryCode = GetCountryCode();
            //CustomerMaster GetValue = new CustomerMaster();
            GetValue.GetStateCode = GetStateCode(GetValue);
            GetValue.GetCompany = GetCompany();
            return View(GetValue);
        }

        // POST: CustomerMasters/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "CustomerCode,CompanyCode,CompanyName,TitleName,FirstName,MiddleName,LastName,AccountCode,CustomerTypeCode,PaymentTermsCode,Address1,Address2,City,StateCode,CountryCode,ZipCode,Phone,Fax,Email,WebSite,CreditCardNo,ExpiryDate,Taxable,ShipToAddress1,ShipToAddress2,ShipToCity,ShipToStateCode,ShipToCountryCode,ShipToZipCode,Remarks,BalanceAmount,InActive,CreatedUser,CreatedDate,ModifiedUser,ModifiedDate,OPENBAL,EXCHANGERATE,FAMILYCODE,CreatedInFinacs,Comments,SSN,EmpTypeId,EmpGroupId,DepartmentId,BankAccountNo,BankName,PayCycle,BirthDay,NoOfDependents,MaritalStatus,DateOfJoin,Released,ReleasedOn,ReleasedRemarks,APAccount,CustomField1,CustomField2,CustomField3,CustomField4,CustomField5,CustomField6,CustomField7,CustomField8,CustomField9,CustomField10,CustomField11,CustomField12,CustomField13,CustomField14,CustomField15,ContactPersonName,ContactGUID,APFamilyCode,StatusID")] CustomerMaster customerMaster)
        public ActionResult Create([Bind(Include = "CustomerCode,CompanyCode,CompanyName,Address1,Address2,City,StateCode,CountryCode,ZipCode,Phone,Fax,Email,InActive,CreatedDate")] CustomerMaster customerMaster)
        {
            if (ModelState.IsValid)
            {
                db.CustomerMaster.Add(customerMaster);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(customerMaster);
        }

        // GET: CustomerMasters/Edit/5
        public ActionResult Edit(string customercode,string companycode)
        {
            if (customercode == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustomerMaster customerMaster = db.CustomerMaster.Find(customercode,companycode);
            if (customerMaster == null)
            {
                return HttpNotFound();
            }
            return View(customerMaster);
        }

        // POST: CustomerMasters/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CustomerCode,CompanyCode,CompanyName,Address1,Address2,City,StateCode,CountryCode,ZipCode,Phone,Fax,Email,InActive,CreatedDate")] CustomerMaster customerMaster)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customerMaster).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customerMaster);
        }

        // GET: CustomerMaster/Delete/5
        public ActionResult Delete(string customercode, string companycode)
        {
            if (customercode == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustomerMaster customerMaster = db.CustomerMaster.Find(customercode, companycode);
            if (customerMaster == null)
            {
                return HttpNotFound();
            }
            return View(customerMaster);
        }

        // POST: CustomerMaster/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string customercode, string companycode)
        {
            try
            {
                CustomerMaster customerMaster = db.CustomerMaster.Find(customercode, companycode);
                db.CustomerMaster.Remove(customerMaster);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                return View("Error", new HandleErrorInfo(ex, "CustomerMastersController", "Index"));

            }
        }
        public ActionResult List()
        {
            return View(db.CustomerMaster.ToList());
        }
        private static List<SelectListItem> GetCountryCode()
        {
            List<SelectListItem> items = new List<SelectListItem>();
            string constr = ConfigurationManager.ConnectionStrings["FMSARABICEntities"].ConnectionString;
            using (SqlConnection con = new SqlConnection(constr))
            {
                string query = " SELECT distinct CountryName, CountryCode FROM CountryMaster";
                using (SqlCommand cmd = new SqlCommand(query))
                {
                    cmd.Connection = con;
                    con.Open();
                    using (SqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            items.Add(new SelectListItem
                            {
                                Text = sdr["CountryName"].ToString(),
                                Value = sdr["CountryCode"].ToString()
                            });
                        }
                    }
                    con.Close();
                }
            }

            return items;
        }
        private static List<SelectListItem> GetStateCode(CustomerMaster cm)
        {
            List<SelectListItem> items = new List<SelectListItem>();
            string constr = ConfigurationManager.ConnectionStrings["FMSARABICEntities"].ConnectionString;
            SqlConnection con = new SqlConnection(constr);
            //SqlCommand cmd = new SqlCommand();
            //cmd.Connection = con;
            //cmd.CommandType = System.Data.CommandType.StoredProcedure;
            //cmd.CommandText = "stpMas_GetAllStateName";

            SqlCommand cmd = new SqlCommand("stpMas_GetAllStates", con);
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            //ObjectParameter op3 = new ObjectParameter("RECORDCOUNT", typeof(int));
            //cmd.Parameters.AddWithValue("@RecordCount", op3);

            SqlParameter recordcount = new SqlParameter();
            recordcount.ParameterName = "@RECORDCOUNT";// Defining Name
            recordcount.SqlDbType = SqlDbType.Int; // Defining DataType
            recordcount.Direction = ParameterDirection.Output;// Setting the direction 
            cmd.Parameters.Add(recordcount);


            //add any parameters the stored procedure might require
            //cmd.Parameters.Add(new SqlParameter("@parameter1", token));
            cmd.Connection = con;
            con.Open();


            using (SqlDataReader sdr = cmd.ExecuteReader())
            {
                while (sdr.Read())
                {
                    items.Add(new SelectListItem
                    {
                        Text = sdr["StateName"].ToString(),
                        Value = sdr["StateCode"].ToString()
                    });
                }
            }
            con.Close();

            return items;
        }
        private static List<SelectListItem> GetCompany()
        {
            List<SelectListItem> items = new List<SelectListItem>();
            string constr = ConfigurationManager.ConnectionStrings["FMSARABICEntities"].ConnectionString;
            using (SqlConnection con = new SqlConnection(constr))
            {
                string query = " SELECT distinct CompanyName, CompanyCode FROM CompanySetup";
                using (SqlCommand cmd = new SqlCommand(query))
                {
                    cmd.Connection = con;
                    con.Open();
                    using (SqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            items.Add(new SelectListItem
                            {
                                Text = sdr["CompanyName"].ToString(),
                                Value = sdr["CompanyCode"].ToString()
                            });
                        }
                    }
                    con.Close();
                }
            }

            return items;
        }

        //public ActionResult AddCustomer(CustomerMaster cm)

DemoMaster/Views/CustomerMasters/AjaxAddList.cshtml
@model DemoMaster.Models.CustomerMaster
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel=" stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.js"></script>

<script src="~/Scripts/DemoScript/AddCustomer.js"></script>
<script src="~/Scripts/DemoScript/js.cookie.js"></script>
<h2>Index</h2>
<p id="demo">JavaScript can change HTML content.</p>
<button type="button" onclick='document.getElementById("demo").innerHTML = "Hello JavaScript!"'>Click Me!</button>
<button type="button" onclick='onBtnClick()'>Click</button>
<span id="message"></span>
<input id="txttrest" type="text" onkeydown="keyDown(event)">
<ul id="fruitList">
    <li>Apple</li>
    <li>Orange</li>
    <li>Grapes</li>
</ul>
<div class="form-group">
    <label>CustomerCode </label><input id="txtCustomerCode" type="text">
    <br />
    <label>CompanyCode</label><input id="txtCompanyCode" type="text">
    <br />
    <label>CompanyName</label><input id="txtCompanyName" type="text">
    <br />
    <label>Address1</label><input id="txtAddress1" type="text">
    <br />
    <label>Address2</label><input id="txtAddress2" type="text">
    <br />
    <label>City</label><input id="txtCity" type="text">
    <br />
    <label>StateCode</label><input id="txtStateCode" type="text">
    <br />
    <label>CountryCode</label><input id="txtCountryCode" type="text">
    <br />
    <label>ZipCode</label><input id="txtZipCode" type="text">
    <br />
    <label>Phone</label><input id="txtPhone" type="text">
    <br />
    <label>Fax</label><input id="txtFax" type="text">
    <br />
    <label>Email</label><input id="txtEmail" type="text">
    <br />
    <label>InActive</label><input id="txtInActive" type="text">
    <br />
    <label>CreatedDate</label><input id="txtCreatedDate" type="text">
    <br />
    <button id="btnFormSubmit">Submit</button>

    <br />
</div>

    <table id="tblEmp">
        <thead>
            <tr>
                <th>CustomerCode</th>
                <th>CompanyCode</th>
                <th>CompanyName</th>
                <th>Address1</th>
                <th>Address2</th>
                <th>City</th>
                <th>StateCode</th>
                <th>CountryCode</th>
                <th>ZipCode</th>
                <th>Phone</th>
                <th>Fax</th>
                <th>Email</th>
                <th>InActive</th>
                <th>CreatedDate</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>

    <style type="text/css">
        form {
            margin: 20px 0;
        }

            form input, button {
                padding: 5px;
            }

        table {
            width: 100%;
            margin-bottom: 20px;
            border-collapse: collapse;
        }   

        table, th, td {
            border: 1px solid #cdcdcd;
        }

            table th, table td {
                padding: 10px;
                text-align: left;
            }

        .txtstyle {
            background-color: aqua;
        }
    </style>

DemoMaster/Views/CustomerMasters/Create.cshtml
@model DemoMaster.Models.CustomerMaster

@{
    Layout = null;
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="css/materialize.min.css" media="screen,projection" />
    <link type="text/css" rel="stylesheet" href="css/style_5.css" media="screen,projection" />
    <link type="text/css" rel="stylesheet" href="css/dashboard_style.css" media="screen,projection" />
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body onLoad="buildHtmlTable()">
    <!--pre loader-->
    <div class="preloader-background">
        <div id="loading"></div>
    </div>
</body>

</html> 

<h2>Create</h2>

@*@using (Html.BeginForm("AddCustomer", "CustomerMasters", FormMethod.Post))*@

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Customer Registration</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CustomerCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerCode,"txtCustomerCode", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerCode, "", new { @class = "text-danger" })
            </div>
        </div>



        @*@Html.HiddenFor(model => model.CompanyCode, new { id = "CompanyCode", Value = @Model.CompanyCode})
        @Html.HiddenFor(model => model.CompanyCode)

        <input data-val="true"
               data-val-number="The field CompanyCode must be a string."
               data-val-required="The CompanyCode field is required."
               id="CompanyCode"
               name="CompanyCode"
               type="hidden"
               value="001" />*@


        <div class="form-group">
           @Html.LabelFor(model => model.CompanyCode,"School Name",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.CompanyCode, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(model => model.CompanyCode, Model.GetCompany, "Please select", "txtCompanyCode")
                @Html.ValidationMessageFor(model => model.CompanyCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyName, "Customer Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompanyName, "txtCompanyName", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address1, "txtAddress1", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address2, "txtAddress2", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, "txtCity", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StateCode, "State Name",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.StateCode, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(model => model.StateCode, Model.GetStateCode, "Please select", "txtStateCode")
                @Html.ValidationMessageFor(model => model.StateCode, "", new { @class = "text-danger" })
            </div>
        </div>

        
        <div class="form-group">
            @Html.LabelFor(model => model.CountryCode,"Country Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.DropDownList("CountryCode", null, htmlAttributes:  new { @class = "form-control" })*@
                @Html.ValidationMessageFor(model => model.CountryCode, "", new { @class = "text-danger" })
                @Html.DropDownListFor(model => model.CountryCode, Model.GetCountryCode, "Please select")
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ZipCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ZipCode, "txtZipCode", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, "txtPhone", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fax, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fax, "txtFax", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fax, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, "txtEmail", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.InActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.InActive, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InActive, "", new { @class = "text-danger" })*@
                <div class="form-group">
                    <div class="radio-inline">
                        @Html.RadioButton("InActive", "Y", true,new { id = "IsInActive" }) Yes
                    </div>
                    <div class="radio-inline">
                        @Html.RadioButton("InActive", "N",new { id = "IsActive" }) No
                    </div>
                </div>

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.CreatedDate, new { htmlAttributes =  new { @class = "datepicker"  } })*@
                @Html.EditorFor(model => model.CreatedDate, "txtCreatedDate", new { htmlAttributes = new { @class = "form-control oso", @type = "date" } })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<button type="button" onclick='onFormSubmit()'>Submit</button>

<div>
    @Html.ActionLink("Back to List", "Index")
    
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DemoMaster/Views/CustomerMasters/Delete.cshtml
@model DemoMaster.Models.CustomerMaster

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CustomerMaster</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @*@Html.DisplayNameFor(model => model.CompanyName)*@
            @Html.DisplayName("CustomerName")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Address1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StateCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StateCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CountryCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CountryCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZipCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fax)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fax)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DemoMaster/Views/CustomerMasters/List.cshtml
@*----------------------------------------------------------------------
@model IEnumerable<DemoMaster.Models.CustomerMaster>

@{
    Layout = null;
    ViewBag.Title = "Index";
    //Layout = "~/Views/Shared/_Finacs.cshtml";
}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="~/Scripts/DemoScript/DemoJS.js"></script>
<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<p id="demo">JavaScript can change HTML content.</p>
<button type="button" onclick='document.getElementById("demo").innerHTML = "Hello JavaScript!"'>Click Me!</button>
<button type="button" onclick='onBtnClick()'>Click</button>
<span id="message"></span>
<input id="txttrest" type="text" onkeydown="keyDown(event)">
<label>CustomerCode </label><input id="txtCustomerCode" type="text">
<button type="button" onclick='onFormSubmit()'>Submit</button>

----------------------------------------------------------------------*@